### ISSUE TITLE
If I just decode the downloaded xml file

### ISSUE THREAD

**Issue by mrvson** [sapphire-bt/hitv-subtitles#1]
I came across your article by chance. Yes, but the episode cannot be viewed on the computer so I can only watch it on my phone and there is a subtile xml file. I asked if there was a file just to decode this xml file, I don't know much about code.

**Comment by sapphire-bt** [comment]
In short: probably not.

I've never used the HiTV app so I can't say for sure, but assuming it uses the same encryption/decryption process then it's not possible to decrypt standalone files without their encryption keys.

I don't plan on reverse engineering the app as it would be too time-consuming. Sorry.
